### ISSUE TITLE
Search strings in Replay do not persist after replaying request.

### ISSUE THREAD

**Issue by douglasday** [caido/caido#747] opened 2024-02-06 23:24 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

When you have a Cmd-F search going in Replay, the search term does not persist when a request is replayed.

### How to reproduce

1. Have a request in Replay
2. In the `Response` box, do a Ctrl/Cmd-F to search for some string in the response.
3. Hit Next to go to another instance of that string in the response
4. Alter the request in some way and replay it.
5. See that the original search term was replaced with another string.

### Environment & setup

OS: MacOS
OS version: 14.3
Caido client: MacOS Desktop
Caido version: 0.30.4

**Comment by Corb3nik** [comment] 2024-02-06 23:58
I believe this is a duplicate of https://github.com/caido/caido/issues/735 , which will be fixed in the next release.

**Closed** 2024-02-07 23:07 UTC
