### ISSUE TITLE
Allow for same shortcuts hotkeys to exist on two or more shortcuts

### ISSUE THREAD

**Issue by Riddle1001** [caido/caido#706] opened 2024-01-08 21:31 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
Allow for same the shortcuts hotkeys to exist on two or more shortcuts. e.g setting CTRL + R for Go to replay **and** Send to replay
![image](https://github.com/caido/caido/assets/75004732/c93f5fb8-f69a-4100-ad5e-5f2198e8120a)

**Comment by Corb3nik** [comment] 2024-03-21 15:40
Closing this as duplicate of #644

**Closed by Corb3nik** 2024-03-21 15:40 UTC
Labels: component: frontend, topic: shortcut, kind: enhancement, effort: medium
