### ISSUE TITLE
HTTP History Scope selector glitches when Filters sidebar is open

### ISSUE THREAD

**Issue by nonsleepr** [caido/caido#554] opened 2023-08-10 12:13 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

HTTP History Scope selector glitches when Filters sidebar is open. The Scope selector doesn't look disabled but shows and disappears right away when interacted with.

### How to reproduce

1. Open HTTP History tab.
2. Open Filters
3. Try to change the scope.
4. Observe the scope selector blink.

### Environment & setup

OS: Windows
OS version: 11
Caido client: Caido Desktop
Caido version: 0.27.2

**Comment by nonsleepr** [comment] 2023-08-10 12:14
Same behavior in Logging/Search.

**Comment by Corb3nik** [comment] 2023-11-09 17:01
Duplicate of #484

**Closed by Corb3nik** 2023-11-09 17:01 UTC
Labels: kind: bug, component: frontend, bug: 2-confirmed, effort: medium
