### ISSUE TITLE
Sorting through response length.

### ISSUE THREAD

**Issue by alexsmith6846759** [caido/caido#729] opened 2024-01-30 15:49 UTC
### Use cases

I believe incorporating a feature in your Burp Suite-like tool that enables sorting responses by length would be valuable. This functionality could prove helpful in various scenarios, such as optimizing analysis processes or identifying anomalies in data patterns.

**Comment by Corb3nik** [comment] 2024-02-09 22:11
Closing this as duplicate of #532

**Closed by Corb3nik** 2024-02-09 22:11 UTC
Labels: component: backend, component: frontend, kind: enhancement, effort: medium, topic: sort
