### ISSUE TITLE
Add HTTPQL filtering to automate results table

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#887] opened 2024-03-26 16:26 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Add HTTPQL filtering to automate results table

### Use cases

Filtering responses based on status code, if they contain a word etc

**Comment by Corb3nik** [comment] 2024-03-26 16:57
Duplicate of https://github.com/caido/caido/issues/219

**Closed by Corb3nik** 2024-03-26 16:57 UTC
