### ISSUE TITLE
Wrapped lines selection styling is missing a part

### ISSUE THREAD

**Issue by Sytten** [caido/caido#480] opened 2023-06-13 18:35 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

[Discord](https://discord.com/channels/843915806748180492/897575154526330960/1118245926193082418)
![image](https://github.com/caido/caido/assets/2366731/89a5866a-2e1b-4c78-bd53-bbfa72ef32f1)

### How to reproduce

Place a cursor at the end and drag it

### Environment & setup

Caido version: 0.26.0

**Comment by Corb3nik** [comment] 2023-07-24 20:17
I can reproduce this on Chrome on macOS. Can't reproduce on Firefox/Safari

**Comment by Corb3nik** [comment] 2024-02-13 05:35
Duplicate of #738

**Closed by Corb3nik** 2024-02-13 05:35 UTC
Labels: kind: bug, component: frontend, bug: 2-confirmed, topic: request-response
