### ISSUE TITLE
Deleting all entries show loading

### ISSUE THREAD

**Issue by Sytten** [caido/caido#801] opened 2024-02-29 21:44 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

<img width="782" alt="Screenshot 2024-02-29 at 4 43 29 PM" src="https://github.com/caido/caido/assets/2366731/7a4be95b-8d65-45a8-ac31-b83cd860d291">

### How to reproduce

1. Delete all entries in HTTP History

### Environment & setup

Caido version: 0.32.1

**Comment by Corb3nik** [comment] 2024-02-29 22:29
Duplicate of #650

**Closed by Corb3nik** 2024-02-29 22:29 UTC
Labels: kind: bug, component: frontend, bug: 2-confirmed, topic: requests, effort: medium
