### ISSUE TITLE
Hide search option on `Escape`

### ISSUE THREAD

**Issue by rew1nter** [caido/caido#594] opened 2023-09-15 11:12 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
Press the escape key to hide this search menu. Almost everywhere you get to search word, this escape shortcut is present 
![image](https://github.com/caido/caido/assets/64508791/60bf6338-b596-4972-8ef0-31f66efabe65)

**Comment by Corb3nik** [comment] 2023-10-19 18:50
Closing the search menu with escape has always been supported, but only works when you are focused on the correct editor.


Added a highlight on the editor and tables to properly show what you're focused on.

![Image](https://github.com/caido/caido/assets/6225588/fab557b1-54f8-4225-994b-d5bf68a1d0d0)

**Comment by rew1nter** [comment] 2023-10-19 21:33
Interesting. After bringing up the search menu, no matter how many times I select the right editor, it doesn't close the search menu on `Escape`. This is the same for HTTP History editors.

Caido: 0.29.0
Browser: Chrome, Brave

*Please consider making the editor highlight feature optional. This is somehow reducing the beautiful Replay UIs charm :'(*

**Comment by Corb3nik** [comment] 2023-10-20 14:27
Apprently, this behavior isn't related to editor focus and is reproducable on :
- Arch + Chrome/Brave

**Comment by Corb3nik** [comment] 2023-10-20 15:08
Issue seems to be caused by the https://chrome.google.com/webstore/detail/vimium-c-all-by-keyboard/hfjbmagddngcpeloejdejnfgbamkjaeg chrome plugin. Disabling the plugin fixes this.

**Closed by Corb3nik** 2023-10-20 15:08 UTC
Labels: component: frontend, topic: request-response, kind: enhancement, effort: low, topic: ux
