### ISSUE TITLE
Automatically formatting body in replay

### ISSUE THREAD

**Issue by Riddle1001** [caido/caido#693] opened 2023-12-11 16:29 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
Format body (e.g json) on replay tab creation
Format as you type, burp does this, very nice to have

**Comment by Corb3nik** [comment] 2024-02-11 01:39
Closing this as duplicate of https://github.com/caido/caido/issues/294

**Closed by Corb3nik** 2024-02-11 01:39 UTC
Labels: component: frontend, topic: replay, kind: enhancement, effort: medium, topic: ux
