### ISSUE TITLE
Highlight bug in some browsers

### ISSUE THREAD

**Issue by Sytten** [caido/caido#530] opened 2023-07-19 22:11 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Some browser seem to have a bug when selecting the data:

https://github.com/caido/caido/assets/2366731/5b48e02e-e40c-4bab-b0fa-b6793768f9cd

### Environment & setup

ARC browser :
Version 0.112.0 (40064)
Chromium Engine Version 114.0.5735.198
Macos Latest: 13.4.1 (c)

**Comment by Corb3nik** [comment] 2023-08-03 02:36
This is a duplicate of #480

**Closed by Corb3nik** 2023-08-03 02:36 UTC
Labels: kind: bug, component: frontend, bug: 1-repro-available, topic: request-response, effort: medium
