### ISSUE TITLE
Slap HTTPQL in Automate

### ISSUE THREAD

**Issue by rew1nter** [caido/caido#979] opened 2024-04-28 11:54 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
Very necessary. It's hard to live without

### Use cases
HTTPQL in automate

**Comment by Corb3nik** [comment] 2024-04-28 12:51
Duplicate of https://github.com/caido/caido/issues/219 :)

**Closed** 2024-04-28 12:51 UTC

**Comment by rew1nter** [comment] 2024-04-28 13:26
Yeah i knew there was an issue. The bot couldn't find it
