### ISSUE TITLE
Allow user to set the debug flag to display more data in logs to debug

### ISSUE THREAD

**Issue by Sytten** [caido/caido#206] opened 2022-04-27 19:08 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Right now we have a lot of debug information that is never shown to the end user.
This means we can't get proper logs to debug a production issue.
We should thus allow the user to set `DEBUG=true` or `--debug` to print debug logs.

**Comment by Corb3nik** [comment] 2022-08-23 15:42
Duplicate of #243

**Closed by Corb3nik** 2022-08-23 15:42 UTC
Labels: kind: feature, component: backend, topic: debugging
