### ISSUE TITLE
Feature : see the decoded payload when we hover over  the value 

### ISSUE THREAD

**Issue by BugBountyzip** [caido/caido#1301] opened 2024-11-22 16:36 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

We need to see the decoded payload when we hover over  the value 

### Use cases

We need to see the decoded payload when we hover over  the value 

![image](https://github.com/user-attachments/assets/0257f9ca-6e3e-4183-bf7f-32d2d9422cb7)

**Comment by Sytten** [comment] 2024-11-22 18:10
I feel this might be better served by a plugin rather than natively

**Comment by Corb3nik** [comment] 2024-11-24 01:41
Closing this as duplicate of https://github.com/caido/caido/issues/824.

We should definitely have this natively. We can allow plugins to implement their own decoders though

**Closed by Corb3nik** 2024-11-24 01:41 UTC
Labels: kind: plugin
