### ISSUE TITLE
Assign shortcuts to convert workflows

### ISSUE THREAD

**Issue by shriyanss** [caido/caido#862] opened 2024-03-19 14:09 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Allowing users to add shortcuts on the convert workflow can be good. Here's how it might be achieved:-
- Adding a new option to assign shortcuts while creating or editing shortcuts next to the three options (the zoom options for canvas) to assign a shortcut
<img width="1516" alt="image" src="https://github.com/caido/caido/assets/71912662/fa0596e9-6c22-4c9e-a100-0d7ce0802163">
- Making default shortcuts for the included workflows
- Assign a fix key-combinations to be included in the shortcut, like ctrl+option in Mac, or ctrl+alt on Windows/Linux

### Use cases

This is a very frequent action that is done while testing and can increase the user's experience

**Comment by Sytten** [comment] 2024-03-22 14:50
Duplicate of https://github.com/caido/caido/issues/606

**Closed by Sytten** 2024-03-22 14:50 UTC
Labels: kind: duplicate
