### ISSUE TITLE
Host/port changes are ignored when duplicating a request in the replay page

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#86] opened 2021-11-24 15:31 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

It looks like Caido isn't considering host/port changes when a request in the replay page is sent to the replay (aka duplicated).

### How to reproduce

Have a request in the replay.
Change the port or the hostname of that request.
Now click on the request and send it to the replay.
This new request will have the old port or hostname.

Thanks!

**Comment by Corb3nik** [comment] 2024-05-15 20:58
Duplicate of https://github.com/caido/caido/issues/509. Should be fixed now

**Closed by Corb3nik** 2024-05-15 20:58 UTC
Labels: kind: bug, component: backend, component: frontend, bug: 1-repro-available, topic: replay
