### ISSUE TITLE
Add support for websockets

### ISSUE THREAD

**Issue by hashem-mo** [caido/caido#533] opened 2023-07-24 11:57 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
we need a support for web sockets, as there are huge websites are built on almost only websockets

### Use cases
testing websockets messages

**Comment by Sytten** [comment] 2023-07-24 15:38
Duplicate of https://github.com/caido/caido/issues/199

**Closed by Sytten** 2023-07-24 15:38 UTC
