### ISSUE TITLE
Intercept websocket messages

### ISSUE THREAD

**Issue by Sh1Yo** [caido/caido#684] opened 2023-12-06 14:29 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Currently websocket messages aren't intercepted even if queue mode is used.

### Use cases

Intercept & change websocket messages for easier testing.

**Comment by Sytten** [comment] 2023-12-06 14:51
Duplicate of https://github.com/caido/caido/issues/568

**Closed by Sytten** 2023-12-06 14:51 UTC
