### ISSUE TITLE
Add button to close sidebars

### ISSUE THREAD

**Issue by Sytten** [caido/caido#506] opened 2023-06-22 03:29 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

When I watched the stream, the presenter only had half the screen. They dragged the tree sidebar (in relay) to a few pixels in width. It would be better to add a way to close and open easily (with a shortcuts too eventually). They would also probably close the menu sidebar if they could (less problematic).

### Use cases

- More space for smaller screen

**Comment by Corb3nik** [comment] 2023-09-05 23:26
Duplicate of https://github.com/caido/caido/issues/547

**Closed by Corb3nik** 2023-09-05 23:26 UTC
Labels: component: frontend, topic: responsiveness, kind: enhancement, effort: medium
