### ISSUE TITLE
Web UI broken in Automate

### ISSUE THREAD

**Issue by r3t4k3r** [caido/caido#1007] opened 2024-05-03 05:42 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Web UI broken after some steps

### How to reproduce

In Automate start attack, and click 3dots.
![image](https://github.com/caido/caido/assets/86055096/e8b15d52-db51-4123-9580-bcf5a1b179b8)

### Environment & setup

OS: ArchLinux
OS version: no matter
Caido client: Firefox
Caido version:  0.35

**Comment by Sytten** [comment] 2024-05-03 17:45
Duplicate of #997

**Closed by Sytten** 2024-05-03 17:45 UTC
Labels: kind: duplicate
