### ISSUE TITLE
Add HTTPQL in sitemap

### ISSUE THREAD

**Issue by shriyanss** [caido/caido#1060] opened 2024-05-26 03:53 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

HTTPQL in sitemap would help to filter out requests that match a certain condition

### Use cases
This is useful when:-
- Analyzing sitemap for different levels of account: A tester can filter out requests that have a particular cookie or token to see the sitemap for a particular user
- Exclude include requests with a particular text/status to hide errors
- .....

**Comment by Sytten** [comment] 2024-05-26 20:35
Duplicate of https://github.com/caido/caido/issues/465

**Closed by Sytten** 2024-05-26 20:35 UTC
