### ISSUE TITLE
View versions of responses

### ISSUE THREAD

**Issue by Sytten** [caido/caido#495] opened 2023-06-19 13:21 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Like you can view versions of requests, you should be able to view versions of responses.
This is already implemented API-side I think.

**Comment by Corb3nik** [comment] 2023-08-06 21:41
Duplicate of https://github.com/caido/caido/issues/404

**Closed by Corb3nik** 2023-08-06 21:41 UTC
Labels: component: frontend, topic: request-response, kind: enhancement, topic: tamper, effort: medium
