### ISSUE TITLE
Provide option to delete multiple requests in one go from Replay tab.

### ISSUE THREAD

**Issue by urakesh661** [caido/caido#787] opened 2024-02-26 07:44 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

It is not possible to delete multiple requests in one go from replay tab.There should be an option to delete multiple request in one attempt.
Current implementation allows to delete individual requests or all of these.There is no option for multiple requests and not all.

### Use cases

This can save users time if they want to delete multiple requests in one attempt.

**Comment by Corb3nik** [comment] 2024-02-26 13:51
@urakesh661 Thanks for the issue! I'm going to close this as duplicate of https://github.com/caido/caido/issues/612

Please vote on that issue so we can prioritize it :)

**Closed by Corb3nik** 2024-02-26 13:51 UTC
