### ISSUE TITLE
Add ability to Intercept response 

### ISSUE THREAD

**Issue by rew1nter** [caido/caido#581] opened 2023-09-01 09:22 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
Add a way to intercept response while queuing and make it optional. The way Burp does it.

**Comment by Sytten** [comment] 2023-09-01 13:40
Duplicate of https://github.com/caido/caido/issues/230

**Closed by Sytten** 2023-09-01 13:40 UTC
Labels: kind: duplicate
