### ISSUE TITLE
add httpql  in intercept page

### ISSUE THREAD

**Issue by abdulsec** [caido/caido#1029] opened 2024-05-13 18:08 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

I would be great to  add httql filter in    intercep page to show only the request  or path that interest you

### Use cases

showing only the request that interest you with httpql  query without relying only in scope

**Comment by Sytten** [comment] 2024-05-14 16:57
Dupe of https://github.com/caido/caido/issues/580

**Closed by Sytten** 2024-05-14 16:57 UTC
Labels: kind: duplicate

**Comment by Corb3nik** [comment] 2025-06-14 13:23
Duplicate of #580
